# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIs\Email_Control_Panel_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(770, 580)
        Dialog.setMinimumSize(QtCore.QSize(770, 580))
        Dialog.setMaximumSize(QtCore.QSize(770, 580))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 563))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_edit_search.setFont(font)
        self.line_edit_search.setObjectName("line_edit_search")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_search)
        self.table_wdget_email_list = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table_wdget_email_list.setMinimumSize(QtCore.QSize(0, 460))
        self.table_wdget_email_list.setMaximumSize(QtCore.QSize(16777215, 460))
        self.table_wdget_email_list.setObjectName("table_wdget_email_list")
        self.table_wdget_email_list.setColumnCount(0)
        self.table_wdget_email_list.setRowCount(0)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.table_wdget_email_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add_email = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_email.setObjectName("btn_add_email")
        self.horizontalLayout.addWidget(self.btn_add_email)
        self.btn_remove_email = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_remove_email.setObjectName("btn_remove_email")
        self.horizontalLayout.addWidget(self.btn_remove_email)
        self.btn_set_default_email = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_set_default_email.setObjectName("btn_set_default_email")
        self.horizontalLayout.addWidget(self.btn_set_default_email)
        self.btn_refresh_email_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_refresh_email_list.setObjectName("btn_refresh_email_list")
        self.horizontalLayout.addWidget(self.btn_refresh_email_list)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.combo_box_email_default = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_email_default.setMaximumSize(QtCore.QSize(103, 50))
        self.combo_box_email_default.setObjectName("combo_box_email_default")
        self.combo_box_email_default.addItem("")
        self.combo_box_email_default.addItem("")
        self.combo_box_email_default.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_box_email_default)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Email Control Panel"))
        self.label.setText(_translate("Dialog", "search"))
        self.btn_add_email.setText(_translate("Dialog", "Add Email"))
        self.btn_remove_email.setText(_translate("Dialog", "Remove Email"))
        self.btn_set_default_email.setText(_translate("Dialog", "Set Default Email"))
        self.btn_refresh_email_list.setText(_translate("Dialog", "Refresh Email List"))
        self.combo_box_email_default.setItemText(0, _translate("Dialog", "All Emails"))
        self.combo_box_email_default.setItemText(1, _translate("Dialog", "Email Default"))
        self.combo_box_email_default.setItemText(2, _translate("Dialog", "Not Default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
