# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIs\Email_Add_Or_Edit_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 150)
        Dialog.setMinimumSize(QtCore.QSize(540, 150))
        Dialog.setMaximumSize(QtCore.QSize(540, 150))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 133))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_email_address = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_email_address.setMaxLength(253)
        self.line_edit_email_address.setObjectName("line_edit_email_address")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_email_address)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_email_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_email_password.setMaxLength(200)
        self.line_edit_email_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_email_password.setObjectName("line_edit_email_password")
        self.horizontalLayout.addWidget(self.line_edit_email_password)
        self.btn_show_hide_password_line_edit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_show_hide_password_line_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_show_hide_password_line_edit.setObjectName("btn_show_hide_password_line_edit")
        self.horizontalLayout.addWidget(self.btn_show_hide_password_line_edit)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(165, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_save.setMaximumSize(QtCore.QSize(86, 16777215))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_cansle = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cansle.setMaximumSize(QtCore.QSize(86, 16777215))
        self.btn_cansle.setObjectName("btn_cansle")
        self.horizontalLayout_2.addWidget(self.btn_cansle)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.line_edit_confirm_email_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_confirm_email_password.setMaxLength(200)
        self.line_edit_confirm_email_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_confirm_email_password.setObjectName("line_edit_confirm_email_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_confirm_email_password)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.check_box_email_default = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.check_box_email_default.setObjectName("check_box_email_default")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.check_box_email_default)
        self.label_show_error = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_show_error.setText("")
        self.label_show_error.setObjectName("label_show_error")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_show_error)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Email Add"))
        self.label.setText(_translate("Dialog", "Email Address"))
        self.label_2.setText(_translate("Dialog", "Email Password"))
        self.btn_show_hide_password_line_edit.setText(_translate("Dialog", "show"))
        self.btn_save.setText(_translate("Dialog", "Save"))
        self.btn_cansle.setText(_translate("Dialog", "Cansle"))
        self.label_4.setText(_translate("Dialog", "Confirm Email Password"))
        self.check_box_email_default.setText(_translate("Dialog", "Email Default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
