# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIs\SignUp_and_Login_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 200)
        Dialog.setMinimumSize(QtCore.QSize(510, 200))
        Dialog.setMaximumSize(QtCore.QSize(510, 200))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_user_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_user_name.setMaxLength(50)
        self.line_edit_user_name.setObjectName("line_edit_user_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_user_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_edit_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_password.setMaxLength(50)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_password)
        self.label_confirm_password = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_confirm_password.setObjectName("label_confirm_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_confirm_password)
        self.line_edit_confirm_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_edit_confirm_password.setMaxLength(50)
        self.line_edit_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_confirm_password.setObjectName("line_edit_confirm_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_confirm_password)
        self.check_box_show_password = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.check_box_show_password.setObjectName("check_box_show_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.check_box_show_password)
        self.label_show_error = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_show_error.setText("")
        self.label_show_error.setObjectName("label_show_error")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_show_error)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_signup_and_login = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_signup_and_login.setObjectName("btn_signup_and_login")
        self.horizontalLayout.addWidget(self.btn_signup_and_login)
        self.btn_cansle = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_cansle.setObjectName("btn_cansle")
        self.horizontalLayout.addWidget(self.btn_cansle)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.btn_convert_to_login = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_convert_to_login.setObjectName("btn_convert_to_login")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_convert_to_login)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sign Up"))
        self.label.setText(_translate("Dialog", "User Name"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label_confirm_password.setText(_translate("Dialog", "Confirm Password"))
        self.check_box_show_password.setText(_translate("Dialog", "Show Password"))
        self.btn_signup_and_login.setText(_translate("Dialog", "Sign Up"))
        self.btn_cansle.setText(_translate("Dialog", "Cansle"))
        self.btn_convert_to_login.setText(_translate("Dialog", "I have account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
